# Generated by Django 5.1.1 on 2024-09-21 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_is_admin_alter_user_is_staff_and_more'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='prefer',
            field=models.ManyToManyField(blank=True, to='product.product'),
        ),
    ]
