# Generated by Django 5.1.1 on 2024-09-27 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cart_user_cart_customer_cart_selected_product_and_more'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.RemoveField(
            model_name='cart',
            name='selected_product',
        ),
        migrations.AddField(
            model_name='cart',
            name='selected_product',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
    ]
